### ISSUE TITLE
Statuses change permanent attributes

### ISSUE THREAD

**Issue by Vican259** [razage/fabula-ultima-unofficial#52]
Been having an issue with the system where actors who are affected by the Weakened and shaken conditions would have their max and current HP and MP lowered, which i believe should not be the case, this issue could be replicated in a world with no additional modules.
so far with replicating the issue, The shaken condition only appears to lower the Max Mp of player character actors whereas the weakened condition appears to lower the max HP of both player character actors and NPC actors.

**Comment by razage** [comment]
Weakened lowers your MIG by one die size and Shaken lowers your WLP by one die size. HP and MP are being automatically calculated, which is why this is happening. I thought that was how the game was supposed to work, but it turns out I'm wrong. 

On Pg. 163, it says that temporary adjustments of stats does **not** change the max values. I will need to put in some thought for how I will handle that. Thanks for bringing it to my attention.

**Comment by razage** [comment]
I have figured out how to handle this and it turns out that I probably had it correct a long time ago. Companions and Grand Summons had the formulas correct, so it was a simple fix to make NPCs and Players correct as well. This has been addressed in c76127a. 

Please update your installation to version 0.8.23b to see this change reflected. Thank you.
