### ISSUE TITLE
[request]Hope to add the function of hit results and automatic calculation of damage to HP

### ISSUE THREAD

**Issue by moroboshikan** [razage/fabula-ultima-unofficial#59]
[This article is written using translation software and may not be expressed clearly.]

In fact, many systems have a feature that automatically displays hits or misses on message cards, and the damage they cause is automatically deducted from HP with just one click of a button.

I am thinking that since FU only has three types of damage states: normal damage, complete absorption, and half damage (immunity does not require HP calculation).

FVTT only needs to press T to select the other party as the target and compare their data.

I'm wondering if it's possible to refactor the message card to some extent and add a new one afterwards

Result: Hit/Missed/Absorbed!

[Damage] [Half damage] [Absorption] "

Such additional messages (buttons inside [], a total of three)

How about it? If you need it, I think I can write a script to temporarily achieve a certain effect and demonstrate it to you

——Players from other countries who also love FU rules

**Comment by moroboshikan** [comment]
As a reward, I can provide a complete art design for your character card. I am a graphic designer and I am quite skilled in designing character cards to make them more in line with the original style

**Comment by razage** [comment]
Hopefully this translates well for you. Each system for Foundry needs to choose how much automation it has. I chose to be light on automation, since this isn't meant to be a tactical strategic game.

Handling attacks would be relatively easy. The problem is with spells and items. Some spells don't deal damage, but change how the target takes damage. And items don't roll anything currently, but shards explicitly do 10 damage. Not to mention dismissing Arcana. Even worse would be the rare items or NPC skills that cause attackers to take damage; I'm not really sure how I'd even approach that.

This wouldn't be a small change and would require quite a bit of work. I cannot commit that kind of time right now, so it definitely wouldn't happen soon. I would happily look over a pull request if someone else wants to implement this though.

PS: I made the character card look that way on purpose. I'm no artist or designer, but I *could have* made it look differently. I wanted it to look like old Final Fantasy. I also didn't want to take any assets from Need Games or the author, so I wanted the UI to be distinct.
